version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: instagram-sorteos-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/usr/share/nginx/html:ro
      - ./nginx-custom.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - web-network

networks:
  web-network:
    driver: bridge